export const SCHEMA_VERSION = 4;

export const createModuleMetadata = (overrides = {}) => ({
  moduleId: "algebra-foundations",
  title: "Algebra Foundations",
  subject: "mathematics",
  focus: "linear equations",
  description: "A bounded algebra module covering variables, expressions, and linear equations.",
  versionTag: "algebra-foundations-v1",
  ...overrides,
});

export const createMasteryRecord = (overrides = {}) => ({
  score: 0,
  status: "available",
  attempts: 0,
  lastPracticedAt: null,
  reviewDueAt: null,
  supportReason: null,
  ...overrides,
});

export const createAssessmentAttemptRecord = (overrides = {}) => ({
  attemptId: null,
  objectiveId: null,
  conceptId: null,
  inputType: "unknown",
  learnerResponse: null,
  result: "pending",
  misconceptionTag: null,
  source: "diagnostic",
  relatedInteractionIds: [],
  recordedAt: null,
  ...overrides,
});

export const createEvidenceRecord = (overrides = {}) => ({
  evidenceId: null,
  conceptId: null,
  objectiveId: null,
  lessonId: null,
  source: "unknown",
  delta: 0,
  misconceptionTags: [],
  supportReason: null,
  relatedInteractionIds: [],
  recordedAt: null,
  ...overrides,
});

export const createRecentInteractionMemoryEntry = (overrides = {}) => ({
  interactionId: null,
  role: "user",
  content: "",
  conceptId: null,
  objectiveId: null,
  recordedAt: null,
  ...overrides,
});

export const createStateShape = (overrides = {}) => ({
  schemaVersion: SCHEMA_VERSION,
  learnerProfile: {
    learnerId: "local-learner",
    locale: "en-GB",
    interests: [],
    avatarSeed: null,
    preferredModalities: ["audio", "visual", "interactive"],
    ...overrides.learnerProfile,
  },
  moduleSelection: {
    selectedModuleId: "algebra-foundations",
    availableModuleIds: ["algebra-foundations"],
    moduleMetadataById: {
      "algebra-foundations": createModuleMetadata(),
    },
    selectedAt: null,
    ...overrides.moduleSelection,
  },
  pedagogicalState: {
    diagnosticStatus: "not-started",
    diagnosticStep: 0,
    readiness: "unknown",
    prerequisiteGaps: [],
    likelyMisconceptions: [],
    diagnosticSummary: null,
    currentConceptId: "variables-and-expressions",
    currentLessonId: null,
    currentObjectiveId: "diagnostic.variables",
    recommendedConceptId: "variables-and-expressions",
    masteryByConcept: {},
    misconceptionsByConcept: {},
    evidenceLog: [],
    reviewSchedule: [],
    recentActivity: [],
    tutoringDecisions: [],
    lessonRecords: {},
    assessmentItems: {},
    assessmentAttempts: [],
    attemptLog: [],
    goals: [],
    milestones: [
      {
        id: "complete-diagnostic",
        label: "Complete the algebra diagnostic",
        status: "active",
      },
      {
        id: "master-first-concept",
        label: "Master your first algebra concept",
        status: "upcoming",
      },
    ],
    ...overrides.pedagogicalState,
  },
  runtimeSession: {
    activeSceneId: null,
    lastScene: null,
    recentTurns: [],
    recentInteractionMemory: [],
    runningSummary: null,
    pendingAssetJobs: [],
    ...overrides.runtimeSession,
  },
  consentAndSettings: {
    cloudEnabled: true,
    cloudImageEnabled: true,
    cloudVisionEnabled: false,
    telemetryEnabled: false,
    adminPinEnabled: false,
    adminPinHash: null,
    adminUnlocked: false,
    captionsEnabled: true,
    soundEnabled: true,
    storagePersistenceGranted: "unknown",
    ...overrides.consentAndSettings,
  },
  providerConfig: {
    providerName: "openrouter",
    modelName: "",
    endpointUrl: "",
    apiKey: "",
    hasStoredApiKey: false,
    configuredAt: null,
    ...overrides.providerConfig,
  },
  capabilities: {
    tier: "minimal",
    webgpu: false,
    opfs: false,
    indexedDb: true,
    localTTS: true,
    localSTT: false,
    microphone: false,
    ...overrides.capabilities,
  },
  assetIndex: {
    manifestVersion: 1,
    byId: {},
    quotaEstimate: null,
    ...overrides.assetIndex,
  },
  exportMetadata: {
    lastExportedAt: null,
    lastImportedAt: null,
    exportFormatVersion: 2,
    ...overrides.exportMetadata,
  },
});
