export const SCHEMA_VERSION = 2;

export const createMasteryRecord = (overrides = {}) => ({
  score: 0,
  status: "available",
  attempts: 0,
  lastPracticedAt: null,
  reviewDueAt: null,
  ...overrides,
});

export const createStateShape = (overrides = {}) => ({
  schemaVersion: SCHEMA_VERSION,
  learnerProfile: {
    learnerId: "local-learner",
    locale: "en-GB",
    interests: [],
    avatarSeed: null,
    preferredModalities: ["audio", "visual", "interactive"],
    ...overrides.learnerProfile,
  },
  moduleSelection: {
    selectedModuleId: "algebra-foundations",
    availableModuleIds: ["algebra-foundations"],
    selectedAt: null,
    ...overrides.moduleSelection,
  },
  pedagogicalState: {
    diagnosticStatus: "not-started",
    diagnosticStep: 0,
    readiness: "unknown",
    currentConceptId: "variables-and-expressions",
    currentLessonId: null,
    currentObjectiveId: "diagnostic.variables",
    recommendedConceptId: "variables-and-expressions",
    masteryByConcept: {},
    misconceptionsByConcept: {},
    evidenceLog: [],
    reviewSchedule: [],
    recentActivity: [],
    lessonRecords: {},
    assessmentItems: {},
    attemptLog: [],
    goals: [],
    milestones: [
      {
        id: "complete-diagnostic",
        label: "Complete the algebra diagnostic",
        status: "active",
      },
      {
        id: "master-first-concept",
        label: "Master your first algebra concept",
        status: "upcoming",
      },
    ],
    ...overrides.pedagogicalState,
  },
  runtimeSession: {
    activeSceneId: null,
    lastScene: null,
    recentTurns: [],
    runningSummary: null,
    pendingAssetJobs: [],
    ...overrides.runtimeSession,
  },
  consentAndSettings: {
    cloudEnabled: true,
    cloudImageEnabled: true,
    cloudVisionEnabled: false,
    telemetryEnabled: false,
    adminPinEnabled: false,
    adminPinHash: null,
    adminUnlocked: false,
    captionsEnabled: true,
    soundEnabled: true,
    storagePersistenceGranted: "unknown",
    ...overrides.consentAndSettings,
  },
  providerConfig: {
    providerName: "openrouter",
    modelName: "",
    endpointUrl: "",
    apiKey: "",
    configuredAt: null,
    ...overrides.providerConfig,
  },
  capabilities: {
    tier: "minimal",
    webgpu: false,
    opfs: false,
    indexedDb: true,
    localTTS: true,
    localSTT: false,
    microphone: false,
    ...overrides.capabilities,
  },
  assetIndex: {
    manifestVersion: 1,
    byId: {},
    quotaEstimate: null,
    ...overrides.assetIndex,
  },
  exportMetadata: {
    lastExportedAt: null,
    lastImportedAt: null,
    exportFormatVersion: 1,
    ...overrides.exportMetadata,
  },
});
